# Config file for automatic testing at travis-ci.org

language: python

dist: xenial

addons:
  postgresql: "10"

install:
  - pip install -r requirements/travis.txt

script:
  - sudo su - postgres -c "psql -c \"CREATE USER djangopsi WITH PASSWORD 'dev1' SUPERUSER;\""
  - sleep 10
  - python test_manage.py test

after_success:
  - codecov
