# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=master
  - DJANGO=2.2
  - DJANGO=2.1
  - DJANGO=2.0

matrix:
  allow_failures:
    - env: DJANGO=master

addons:
  postgresql: "10"

install:
  - pip install -r requirements/travis.txt

script:
  - sudo su - postgres -c "psql -c \"CREATE USER djangopsi WITH PASSWORD 'dev1' SUPERUSER;\""
  - sleep 10
  - tox

after_success:
  - codecov
